POST http://localhost:3333/videos
Content-Type: application/json
 
{
    "title" : "Video 01",
    "description" : "Este é o video 01",
    "duration" : 180
}

###

GET  https://node-do-0-d2o9.onrender.com/videos?search=01

###

PUT https://node-do-0-d2o9.onrender.com/videos/7860417c-8393-4c40-82cb-08d00476f433
Content-Type: application/json
 
{
    "title" : "Video node",
    "description" : "Este é o video node",
    "duration" : 180
}

###

DELETE https://node-do-0-d2o9.onrender.com/videos/dfeeef07-fa6c-4dd0-b55f-3d7ba6745bd5
